# Generated by Django 3.2.9 on 2021-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_rank', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('teaching', models.DecimalField(decimal_places=10, max_digits=19)),
                ('international', models.DecimalField(decimal_places=10, max_digits=19)),
                ('research', models.DecimalField(decimal_places=10, max_digits=19)),
                ('citations', models.DecimalField(decimal_places=10, max_digits=19)),
                ('income', models.DecimalField(decimal_places=10, max_digits=19)),
                ('total_score', models.DecimalField(decimal_places=10, max_digits=19)),
                ('num_students', models.IntegerField()),
            ],
        ),
    ]
