# Generated by Django 3.2.9 on 2021-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211111_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='url',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
