# Generated by Django 3.2.9 on 2021-11-11 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_college_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together={('user', 'college')},
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='category',
        ),
    ]
